version: '3.7'

services:
    # PBX
    issabel:
        image: technoexpress/issabel-pbx
#        build: ./
        restart: always
        container_name: pbx_issabel
#        network_mode: host
        cap_add:
          - NET_ADMIN
        privileged: true
        hostname: pbx.example
        expose:
          - "25"    # SMTPS - mostly processing incoming mails
#          - "22"  # SSH - puerto ssh
          - "465"    # SMTPS - mostly processing incoming mails
          - "110"  #  POP3 - standard protocol for accessing mailbox, STARTTLS is required before client auth                                >
          - "143"  #  IMAP - standard protocol for accessing mailbox, STARTTLS is required before client auth
          - "587"  #  MSA - SMTP port used primarily for email clients after STARTTLS and auth
          - "993"  #  IMAPS - alternative port for IMAP encrypted since connection
          - "995"  #  POP3S - encrypted POP3 since connections
          - "5038" # ASTERISK - puerto usado por asterisk SIP/IAX2
          - "5060/tcp" # SIP - puerto SIP
          - "5060/udp" # SIP - puerto SIP
          - "5061/udp" # SIP - puerto SIP
          - "5061/tcp" # SIP - puerto SIP
          - "8001"
          - "8003"
          - "8088"
          - "8089"
          - "9900/tcp"
          - "9900/udp"
          - "10000-10100/tcp"
          - "10000-10100/udp"
        ports:
          - 89:89  # HTTP - redirect to https (see options) and authentication for Let's encrypt service
          - 8433:8433  #  HTTPS - access to administration or webmail client

        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
          - "issabel-etc:/etc"
          - "issabel-data:/var/lib"
          - "./httpd.conf:/etc/httpd/conf/httpd.conf"
          - "./ssl.conf:/etc/httpd/conf.d/ssl.conf"
        networks:
          - issabel
networks:
 issabel:
   external: true
volumes:
  issabel-etc:
  issabel-data:
